name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job 1 done"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo 2
        run: echo "job 2 done"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo 3
        run: |
          echo "job 3 failed"
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: echo 4
        run: echo "job3 done"